name: ai_browser_agent
description: A powerful AI Agent Browser powered by Chromium and Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  provider: ^6.1.1
  google_generative_ai: ^0.2.0
  url_launcher: ^6.2.0
  iconsax: ^0.0.8
  share_plus: ^9.0.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  permission_handler: ^11.3.0
  speech_to_text: ^6.3.0
  mobile_scanner: ^5.0.0
  path_provider: ^2.1.2
  flutter_tts: ^3.8.5
  wakelock_plus: ^1.1.4
  local_auth: ^2.1.8
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
